  window.ARTIST_IMG = {
    '$uicideboy$': 'images/artist-uicideboy.jpg',
    '100 gecs': 'images/artist-100gecs.jpg',
    'A. G. Cook': 'images/artist-agcook.jpg',
    'Aphex Twin': 'images/artist-aphextwin.jpg',
    'Arca': 'images/artist-arca.jpg',
    'Asian Kung-Fu Generation': 'images/artist-asiankungfugeneration.jpg',
    'BAYNK': 'images/artist-baynk.jpg',
    'BläZy': 'images/artist-blzy.jpg',
    'Bugseed': 'images/artist-bugseed.jpg',
    'Burial': 'images/artist-burial.jpg',
    'Cake Pop': 'images/artist-cakepop.jpg',
    'CoryaYo': 'images/artist-coryayo.jpg',
    'Crystal Castles': 'images/artist-crystalcastles.jpg',
    'DAVICHI': 'images/artist-davichi.jpg',
    'Daughters': 'images/artist-daughters.jpg',
    'David Bowie': 'images/artist-davidbowie.jpg',
    'Dutch Disorder': 'images/artist-dutchdisorder.jpg',
    'Earl Sweatshirt': 'images/artist-earlsweatshirt.jpg',
    'Epik High': 'images/artist-epikhigh.jpg',
    'Floating Points': 'images/artist-floatingpoints.jpg',
    'Florence + The Machine': 'images/artist-florencethemachine.jpg',
    'Frank Ocean': 'images/artist-frankocean.jpg',
    'Freddie Gibbs': 'images/artist-freddiegibbs.jpg',
    'Freddie Gibbs & Madlib': 'images/artist-freddiegibbsmadlib.jpg',
    'Freddie Gibbs & The Alchemist': 'images/artist-freddiegibbs.jpg',
    'Freestylers': 'images/artist-freestylers.jpg',
    'Frou Frou': 'images/artist-froufrou.jpg',
    'J.Rawls': 'images/artist-jrawls.jpg',
    'JPEGMAFIA': 'images/artist-jpegmafia.jpg',
    'James Blake': 'images/artist-jamesblake.jpg',
    'Jan Panenka': 'images/artist-janpanenka.jpg',
    'Joey Bada$$': 'images/artist-joeybada.jpg',
    'Justice': 'images/artist-justice.jpg',
    'Kanye West': 'images/artist-kanyewest.jpg',
    'Kendrick Lamar': 'images/artist-kendricklamar.jpg',
    'Kid Cudi': 'images/artist-kidcudi.jpg',
    'Leessang': 'images/artist-leessang.jpg',
    'M.I.A.': 'images/artist-mia.jpg',
    'Massive Attack': 'images/artist-massiveattack.jpg',
    'Megumi Hayashibara': 'images/artist-megumihayashibara.jpg',
    'Men I Trust': 'images/artist-menitrust.jpg',
    'Mitski': 'images/artist-mitski.jpg',
    'Mount Kimbie': 'images/artist-mountkimbie.jpg',
    'My Bloody Valentine': 'images/artist-mybloodyvalentine.jpg',
    'Niki Istrefi': 'images/artist-nikiistrefi.jpg',
    'Nirvana': 'images/artist-nirvana.jpg',
    'Phoebe Bridgers': 'images/artist-phoebebridgers.jpg',
    'Pigeondust': 'images/artist-pigeondust.jpg',
    'Portishead': 'images/artist-portishead.jpg',
    'RADWIMPS': 'images/artist-radwimps.jpg',
    'Rezz': 'images/artist-rezz.jpg',
    'SZA': 'images/artist-sza.jpg',
    'Shiro Sagisu': 'images/artist-shirosagisu.jpg',
    'Skepta': 'images/artist-skepta.jpg',
    'Smashing Pumpkins': 'images/artist-smashingpumpkins.jpg',
    'Snail Mail': 'images/artist-snailmail.jpg',
    'Soccer Mommy': 'images/artist-soccermommy.jpg',
    'Sufjan Stevens': 'images/artist-sufjanstevens.jpg',
    'Syko': 'images/artist-syko.jpg',
    'Tame Impala': 'images/artist-tameimpala.jpg',
    'The Killers': 'images/artist-thekillers.jpg',
    'Tim Presley': 'images/artist-timpresley.jpg',
    'Trippie Redd': 'images/artist-trippieredd.jpg',
    'Tyler, the Creator': 'images/artist-tylerthecreator.jpg',
    'Vance Joy': 'images/artist-vancejoy.jpg',
    'Weyes Blood': 'images/artist-weyesblood.jpg',
    'Yoko Kanno': 'images/artist-yokokanno.jpg',
    'Yoko Takahashi': 'images/artist-yokotakahashi.jpg',
    'death\'s dynamic shroud': 'images/artist-deathsdynamicshroud.jpg',
  };
